10 homepage testimonials block
aemsites/piramal pull request #27
Opened 2024-07-23 07:48 UTC by mind-adobe

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #10 

Test URLs:
- Before: https://main--piramal--aemsites.hlx.page
- After: https://10-homepage-testimonials-block--piramal--aemsites.hlx.page

2024-07-23 08:44 UTC, asthabh23 requested changes
please merge main branch changes in here and update the fonts used in this block for name/title/description.
The title shouldn't be italic. please compare once with original site again.

2024-07-23 10:20 UTC, asthabh23 commented
still needs a padding fix for the section 

<img width="1785" alt="Screenshot 2024-07-23 at 15 50 09" src="https://github.com/user-attachments/assets/f84d2304-0192-45fc-952e-e705d9de3fec">

2024-07-23 11:03 UTC, asthabh23 commented
@mind-adobe yes, we need to add them!
I was about to mention that

2024-07-23 11:04 UTC, asthabh23 commented
For section padding - I will create a separate issue then so it can be taken care of in one shot

2024-07-23 12:55 UTC, asthabh23 commented
@mind-adobe , please see and address the issues under accessibility: https://pagespeed.web.dev/analysis/https-10-homepage-testimonials-block--piramal--aemsites-hlx-page/926ft22tc1?utm_source=psi&utm_medium=redirect&form_factor=mobile

this gets highlighted in SEO as well

2024-07-24 07:15 UTC, mind-adobe commented
> @mind-adobe , please see and address the issues under accessibility: https://pagespeed.web.dev/analysis/https-10-homepage-testimonials-block--piramal--aemsites-hlx-page/926ft22tc1?utm_source=psi&utm_medium=redirect&form_factor=mobile
> 
> this gets highlighted in SEO as well

Fixed it, should be good now

2024-07-24 07:31 UTC, asthabh23 approved these changes
please remove unrequired comments before merging, rest looks good!

2024-07-24 07:31 UTC, asthabh23 commented on blocks/testimonies/testimonies.css
> +  /* opacity: 0.125; */
please remove unrequired comments

2024-07-24 07:33 UTC, merged