style done for footer component
aemsites/piramal pull request #83
Opened 2024-07-31 13:51 UTC by omprakashgupta1995

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--piramal--aemsites.hlx.page
- After: https://<branch>--piramal--aemsites.hlx.page

2024-08-01 06:00 UTC, asthabh23 requested changes
Few observations on alignment:
1.  on reducing the browser width almost near `900px` , the content alignment needs to be made better.
Please introduce gaps within column so content is clearly visible for each cell.
![Screenshot 2024-08-01 at 11 24 33](https://github.com/user-attachments/assets/6eb55c42-38f2-4e41-858b-f4ecc670f926)

 Original site:
 
![Screenshot 2024-08-01 at 11 25 33](https://github.com/user-attachments/assets/62170ea5-57f7-4fae-abab-cb9f58257db1)

 2. The social media icons need not be wrapped to be moved to next line. (also space between play store icons and right side content needs a recheck)
 
<img width="921" alt="Screenshot 2024-08-01 at 11 27 39" src="https://github.com/user-attachments/assets/93bf1cdf-2241-4377-a858-861e2f392df0">

3. we have added `clickable-images` class in columns block for social media icons - so that logo image followed by link should be wrapped within the link (this needs to be handled in DOM manipulation via JS).Please update so the icons are clickable.

2024-08-01 10:16 UTC, Sk-Zahid commented on blocks/footer/footer.css
> +    font-family: Nunito-Regular, sans-serif;
Variables for font size 16 are not provided for body in styles.css also font weight

2024-08-02 11:42 UTC, mind-adobe commented on blocks/columns/columns.js
> +      if (block.classList.contains('clickable-images')) {
This should be handled in css by making the anchor tag width 100% height 100% and position absolute and displayed over the image. There shouldn't be an event listener for the click event.

2024-08-06 10:36 UTC, mind-adobe commented
There is also a problem regarding columns spacing on some resolutions, please check it out.
<img width="1223" alt="image" src="https://github.com/user-attachments/assets/f4c40431-ee4f-40a8-8a61-7352a5eab8bd">
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/895f5e2f-2c57-438e-93bb-9ac4effab370">

2024-08-06 12:08 UTC, asthabh23 approved these changes
approving, Adobe team to cover the remaining parts

2024-08-06 12:22 UTC, merged